name: "Deploy"

on:
  release:
    types:
      - published
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  vercel:
    runs-on: ubuntu-20.04
    name: "Deployment"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "17"
          registry-url: https://registry.npmjs.org/
      - name: "Deploy to Vercel"
        run: |
        prodRun=""
        if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
          prodRun="--prod"
        fi

        npx vercel --token ${VERCEL_TOKEN} $prodRun
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_ORD_ID: ${{ secrets.VERCEL_ORD_ID }}
